Repository dask/dask-gateway, pull requests merged in 2022-11, with the labels that each got.

#635 Fix invalid wheel name to PEP 600
  dask-gateway-server/setup.py
Labels: bug

#627 Extend integration tests to multi-namespace deployment
  .github/workflows/test.yaml
  tests/kubernetes/test_integration.py
Labels: maintenance

#634 Fix failure to build and publish arm64 images
  .github/workflows/build-publish-helm-chart.yaml
  .github/workflows/test.yaml
  dask-gateway/Dockerfile
  resources/helm/chartpress.yaml
Labels: bug, codebase:helm-chart

#637 Test against golang 1.19, latest slurm, latest hadoop
  .github/workflows/test.yaml
  continuous_integration/docker/README.md
  continuous_integration/docker/base/Dockerfile
  continuous_integration/docker/hadoop/Dockerfile
  continuous_integration/docker/hadoop/_install.sh
  continuous_integration/docker/slurm/Dockerfile
  continuous_integration/docker/slurm/files/etc/slurm/cgroup.conf
  dask-gateway/setup.py
Labels: maintenance

#647 ci: help hadoop/pbs tests become robuster by awaiting startup
  continuous_integration/docker/README.md
  continuous_integration/docker/hadoop/start.sh
  continuous_integration/docker/pbs/start.sh
  continuous_integration/docker/slurm/start.sh
Labels: ci
