Repository dask/dask-gateway, pull requests merged in 2022-03, with the labels that each got.

#490 ci: add dependabot config
  .github/dependabot.yml
Labels: ci

#493 ci: build/push images workflow, added
  .github/workflows/build-publish-images.yaml
Labels: ci

#492 ci: misc updates to test workflow and pytest-asyncio
  .github/workflows/test.yaml
  continuous_integration/docker/hadoop/_install.sh
  continuous_integration/docker/pbs/_install.sh
  continuous_integration/docker/slurm/_install.sh
  continuous_integration/install.sh
  continuous_integration/kubernetes/install.sh
  pyproject.toml
  tests/kubernetes/test_integration.py
  tests/test_auth.py
  tests/test_client.py
  tests/test_db_backend.py
  tests/test_local_backend.py
  tests/test_pbs_backend.py
  tests/test_proxies.py
  tests/test_slurm_backend.py
  tests/test_utils.py
  tests/test_workqueue.py
  tests/test_yarn_backend.py
Labels: ci

#500 ci/docs: updates related to building and testing documentation
  .github/workflows/build-publish-docs.yaml
  .gitignore
  continuous_integration/docker/pbs/Dockerfile
  dask-gateway-server/dask_gateway_server/backends/kubernetes/backend.py
  docs/Makefile
  docs/source/conf.py
  docs/source/develop.rst
  docs/source/index.rst
  docs/source/install-hadoop.rst
  docs/source/install-jobqueue.rst
  docs/source/install-kube.rst
  docs/sphinxext/autodoc_traitlets.py
Labels: documentation, ci

#497 ci: let flake8 be configured in a single place instead of three
  .flake8
  dask-gateway-server/setup.cfg
  dask-gateway/setup.cfg
Labels: ci

#499 Add boilerplate .gitignore from GitHub
  .gitignore
Labels: maintenance

#502 Remove legacy purge flag from k8s uninstall docs
  docs/source/install-kube.rst
Labels: documentation

#501 maint/ci: remove support for Python 3.6 and test against multiple versions of Python and Golang
  .github/workflows/test.yaml
  dask-gateway-server/setup.py
  dask-gateway/setup.py
Labels: maintenance, ci

#503 ci: update black config for python 3.7-3.10
  pyproject.toml
Labels: ci

#505 ci: run go native tests against modern versions of go
  .github/workflows/test.yaml
Labels: ci

#512 ci: add timeout to avoid 6h consequence of intermittent hang issue
  .github/workflows/test.yaml
Labels: ci

#510 Cleanup no longer needed workarounds for Python 3.6
  dask-gateway-server/dask_gateway_server/backends/kubernetes/utils.py
  dask-gateway-server/dask_gateway_server/backends/yarn.py
  dask-gateway-server/dask_gateway_server/compat.py
  dask-gateway-server/dask_gateway_server/utils.py
  tests/test_client.py
  tests/test_db_backend.py
Labels: maintenance

#508 ci, pre-commit: add python style modernizing autoformatter
  .pre-commit-config.yaml
  dask-gateway-server/build_tools/build_manylinux.py
  dask-gateway-server/dask_gateway_server/auth.py
  dask-gateway-server/dask_gateway_server/backends/db_base.py
  dask-gateway-server/dask_gateway_server/backends/jobqueue/launcher.py
  dask-gateway-server/dask_gateway_server/backends/jobqueue/pbs.py
  dask-gateway-server/dask_gateway_server/backends/kubernetes/controller.py
  dask-gateway-server/dask_gateway_server/backends/kubernetes/utils.py
  dask-gateway-server/dask_gateway_server/models.py
  dask-gateway-server/dask_gateway_server/options.py
  dask-gateway-server/dask_gateway_server/utils.py
  dask-gateway-server/dask_gateway_server/workqueue.py
  dask-gateway-server/setup.py
  dask-gateway/dask_gateway/auth.py
  dask-gateway/dask_gateway/client.py
  dask-gateway/dask_gateway/config.py
  dask-gateway/dask_gateway/options.py
  dask-gateway/dask_gateway/scheduler_preload.py
  tests/test_auth.py
  tests/test_pbs_backend.py
  tests/test_proxies.py
  tests/test_slurm_backend.py
  tests/test_utils.py
  tests/utils_test.py
Labels: ci

#517 ci: add fixme notes, update python/go versions, make a script executable like others
  .github/workflows/build-publish-docs.yaml
  .github/workflows/test.yaml
  continuous_integration/install.sh
Labels: ci

#518 ci: use k3s instead of k3d to setup k8s, and test against k8s 1.20-1.23
  .github/workflows/test.yaml
  continuous_integration/kubernetes/helm-install.sh
  continuous_integration/kubernetes/install-tools.sh
  resources/helm/testing/chart-install-values.yaml
Labels: ci
