Repository dask/dask-gateway, pull requests merged in 2022-06, with the labels that each got.

#569 Let Traefik's route traffic across namespaces via IngressRoute resources
  resources/helm/dask-gateway/templates/traefik/deployment.yaml
Labels: codebase:helm-chart

#567 Update docs theme for rebranding
  docs/requirements.txt
  docs/source/conf.py
Labels: documentation

#561 Install bokeh and numpy in the Helm chart's scheduler and worker sample image
  dask-gateway/Dockerfile
Labels: maintenance

#575 Provide frozen requirements.txt files for images, and automation to update them
  .github/workflows/refreeze-dockerfile-requirements-txt.yaml
  RELEASE.md
  dask-gateway-server/Dockerfile
  dask-gateway-server/Dockerfile.requirements.in
  dask-gateway-server/Dockerfile.requirements.txt
  dask-gateway/Dockerfile
  dask-gateway/Dockerfile.requirements.in
  dask-gateway/Dockerfile.requirements.txt
Labels: enhancement, codebase:helm-chart, ci

#573 Fix compatibility with distributed >= 2022.5.1 and traitlets >= 5.2.0, and raise the lower bound of required versions
  dask-gateway-server/dask_gateway_server/app.py
  dask-gateway-server/dask_gateway_server/backends/inprocess.py
  dask-gateway-server/dask_gateway_server/backends/kubernetes/controller.py
  dask-gateway-server/dask_gateway_server/traitlets.py
  dask-gateway-server/dask_gateway_server/utils.py
  dask-gateway-server/requirements.txt
  dask-gateway/requirements.txt
  tests/test_db_backend.py
Labels: bug

#580 Update dask-gateway package's requirements to what works
  dask-gateway/requirements.txt
Labels: bug
