Repository dask/dask-gateway, pull requests merged in 2023-01, with the labels that each got.

#666 Use and fix support for Python 3.11 in Helm chart images
  .github/workflows/build-publish-docs.yaml
  .github/workflows/build-publish-helm-chart.yaml
  .github/workflows/build-publish-python-packages.yaml
  .github/workflows/refreeze-dockerfile-requirements-txt.yaml
  .github/workflows/test.yaml
  continuous_integration/docker/base/Dockerfile
  continuous_integration/docker/hadoop/_install.sh
  continuous_integration/docker/pbs/_install.sh
  continuous_integration/docker/slurm/_install.sh
  dask-gateway-server/Dockerfile
  dask-gateway-server/dask_gateway_server/backends/kubernetes/controller.py
  dask-gateway-server/setup.py
  dask-gateway/Dockerfile
  dask-gateway/setup.py
  dev-environment.yaml
  tests/requirements.txt
  tests/test_pbs_backend.py
  tests/test_slurm_backend.py
  tests/test_yarn_backend.py
Labels: bug

#670 Add changelog for 2023.1.0
  docs/source/changelog.md
Labels: documentation

#672 client: fix failure to display widget with ipywidgets 8
  dask-gateway/dask_gateway/client.py
  dask-gateway/dask_gateway/options.py
Labels: bug, codebase:dask-gateway

#673 Update RELEASE.md to use tbump
  .pre-commit-config.yaml
  RELEASE.md
  pyproject.toml
Labels: maintenance

#674 Add changelog for 2023.1.1
  docs/source/changelog.md
Labels: documentation
