Repository dask/dask-gateway, pull requests merged in 2024-01, with the labels that each got.

#790 ci: make upload/download artifact compatible with new action version
  .github/workflows/build-publish-python-packages.yaml
  docs/source/index.rst
Labels: ci

#792 Update traefik to 2.10.6
  resources/helm/dask-gateway/crds/traefik.yaml
  resources/helm/dask-gateway/values.yaml
Labels: codebase:helm-chart

#795 Fix list not displayed as such in install-kube.rst
  docs/source/install-kube.rst
Labels: documentation

#794 Drop support for k8s 1.24, test against 1.29
  .github/workflows/test.yaml
  resources/helm/dask-gateway/Chart.yaml
Labels: codebase:helm-chart, maintenance, breaking

#799 Fix docs build by pinning indirect dependencies
  docs/requirements.txt
Labels: maintenance

#779 Add changelog for 2024.1.0
  docs/source/changelog.md
Labels: documentation
