Repository dask/dask-gateway, pull requests merged in 2025-01, with the labels that each got.

#839 ci: remove workaround installing pymzq via conda-forge
  continuous_integration/docker/hadoop/_install.sh
  continuous_integration/docker/pbs/_install.sh
  continuous_integration/docker/slurm/_install.sh
Labels: ci

#838 ci: upgrade pip in test images so sqlalchemy etc gets installed
  continuous_integration/docker/hadoop/_install.sh
  continuous_integration/docker/pbs/_install.sh
  continuous_integration/docker/slurm/_install.sh
Labels: ci

#841 Require python 3.10+, up from 3.9+
  .github/workflows/test.yaml
  .pre-commit-config.yaml
  dask-gateway-server/setup.py
  dask-gateway/setup.py
  docs/source/changelog.md
  pyproject.toml
Labels: breaking

#843 ci: fix failure to adopt ubuntu-24.04 runners consistently
  .github/workflows/build-publish-docs.yaml
  .github/workflows/build-publish-helm-chart.yaml
Labels: ci

#844 tests: fix compatibility with modern pytest
  tests/test_client.py
Labels: maintenance

#846 helm-chart: require k8s 1.29+, up from 1.25+
  .github/workflows/test.yaml
  docs/source/changelog.md
  resources/helm/dask-gateway/Chart.yaml
Labels: codebase:helm-chart, breaking

#847 Fix deprecation warning from datetime
  dask-gateway-server/dask_gateway_server/tls.py
Labels: codebase:dask-gateway-server, maintenance

#849 tests: fix no longer supported use of pytest.warns(None)
  tests/test_client.py
Labels: codebase:dask-gateway, maintenance

#836 feat(traefik): bump traefik from 2.10.6 to 3.2.0, update CRDs, and update RBAC
  resources/helm/dask-gateway/crds/traefik.yaml
  resources/helm/dask-gateway/templates/traefik/rbac.yaml
  resources/helm/dask-gateway/values.yaml
Labels: codebase:helm-chart, breaking

#854 chore(python): upgrade as high as it works
  .github/workflows/build-publish-docs.yaml
  .github/workflows/build-publish-helm-chart.yaml
  .github/workflows/build-publish-python-packages.yaml
  .github/workflows/refreeze-dockerfile-requirements-txt.yaml
  .github/workflows/test.yaml
  dask-gateway-server/Dockerfile.requirements.txt
  dask-gateway/Dockerfile
  dask-gateway/Dockerfile.requirements.txt
  dev-environment.yaml
Labels: codebase:helm-chart, maintenance
